"""empty message

Revision ID: 2b72b722e64f
Revises: 331d7e2b4f99
Create Date: 2018-04-01 20:54:53.805000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b72b722e64f'
down_revision = '331d7e2b4f99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('teacheremail', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher', 'teacheremail')
    # ### end Alembic commands ###
