"""empty message

Revision ID: 331d7e2b4f99
Revises: 52047b7e025b
Create Date: 2018-04-01 20:47:44.710000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '331d7e2b4f99'
down_revision = '52047b7e025b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teacher', 'teacherdepartment',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('teacher', 'teacherjob',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('teacher', 'teacherroom',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('teacher', 'teachersex',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teacher', 'teachersex',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('teacher', 'teacherroom',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('teacher', 'teacherjob',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('teacher', 'teacherdepartment',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
