"""empty message

Revision ID: 5097870dcd00
Revises: 
Create Date: 2018-03-27 15:09:38.210995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5097870dcd00'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school', sa.String(length=100), nullable=False),
    sa.Column('teachername', sa.String(length=100), nullable=False),
    sa.Column('teacherphone', sa.String(length=11), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school', sa.String(length=100), nullable=False),
    sa.Column('teamname', sa.String(length=100), nullable=False),
    sa.Column('teacher', sa.String(length=100), nullable=False),
    sa.Column('teacherphone', sa.String(length=11), nullable=False),
    sa.Column('member1', sa.String(length=100), nullable=False),
    sa.Column('member1phone', sa.String(length=11), nullable=False),
    sa.Column('member2', sa.String(length=100), nullable=False),
    sa.Column('member2phone', sa.String(length=11), nullable=False),
    sa.Column('member3', sa.String(length=100), nullable=False),
    sa.Column('member3phone', sa.String(length=11), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team')
    op.drop_table('teacher')
    # ### end Alembic commands ###
