"""empty message

Revision ID: 52047b7e025b
Revises: 
Create Date: 2018-04-01 20:44:25.466000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52047b7e025b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('teacherdepartment', sa.String(length=100), nullable=False))
    op.add_column('teacher', sa.Column('teacherjob', sa.String(length=100), nullable=False))
    op.add_column('teacher', sa.Column('teacherroom', sa.String(length=100), nullable=False))
    op.add_column('teacher', sa.Column('teachersex', sa.String(length=100), nullable=False))
    op.add_column('team', sa.Column('member1email', sa.String(length=100), nullable=False))
    op.add_column('team', sa.Column('member1grade', sa.String(length=100), nullable=False))
    op.add_column('team', sa.Column('member1sex', sa.String(length=100), nullable=False))
    op.add_column('team', sa.Column('member1size', sa.String(length=100), nullable=False))
    op.add_column('team', sa.Column('member1skill', sa.String(length=100), nullable=False))
    op.add_column('team', sa.Column('member2email', sa.String(length=100), nullable=False))
    op.add_column('team', sa.Column('member2grade', sa.String(length=100), nullable=False))
    op.add_column('team', sa.Column('member2sex', sa.String(length=100), nullable=False))
    op.add_column('team', sa.Column('member2size', sa.String(length=100), nullable=False))
    op.add_column('team', sa.Column('member2skill', sa.String(length=100), nullable=False))
    op.add_column('team', sa.Column('member3email', sa.String(length=100), nullable=False))
    op.add_column('team', sa.Column('member3grade', sa.String(length=100), nullable=False))
    op.add_column('team', sa.Column('member3sex', sa.String(length=100), nullable=False))
    op.add_column('team', sa.Column('member3size', sa.String(length=100), nullable=False))
    op.add_column('team', sa.Column('member3skill', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'member3skill')
    op.drop_column('team', 'member3size')
    op.drop_column('team', 'member3sex')
    op.drop_column('team', 'member3grade')
    op.drop_column('team', 'member3email')
    op.drop_column('team', 'member2skill')
    op.drop_column('team', 'member2size')
    op.drop_column('team', 'member2sex')
    op.drop_column('team', 'member2grade')
    op.drop_column('team', 'member2email')
    op.drop_column('team', 'member1skill')
    op.drop_column('team', 'member1size')
    op.drop_column('team', 'member1sex')
    op.drop_column('team', 'member1grade')
    op.drop_column('team', 'member1email')
    op.drop_column('teacher', 'teachersex')
    op.drop_column('teacher', 'teacherroom')
    op.drop_column('teacher', 'teacherjob')
    op.drop_column('teacher', 'teacherdepartment')
    # ### end Alembic commands ###
